import { Dimensions, StyleSheet } from 'react-native';

import { BLUE, BLUE_DARK, GREEN, RED } from './constants';
import { darkColors, lightColors, type ColorPalette } from './theme/colors';
import { useTheme } from './theme/ThemeContext';

const { width } = Dimensions.get('window');
export const phoneWidth = Math.min(width - 28, 390);

function buildStyles(c: ColorPalette) {
  return StyleSheet.create({
    app: {
      flex: 1,
      backgroundColor: c.appBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    phone: {
      width: phoneWidth,
      maxWidth: 390,
      height: '100%',
      backgroundColor: c.surface,
      overflow: 'hidden',
    },
    phoneDark: {
      backgroundColor: BLUE_DARK,
    },
    splashFrame: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: BLUE_DARK,
    },
    loadingBody: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    splashBody: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 58,
    },
    brandMark: {
      width: 110,
      height: 84,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    brandShield: {
      position: 'absolute',
      right: 16,
      bottom: 0,
    },
    splashTitle: {
      color: '#ffffff',
      fontSize: 36,
      fontWeight: '800',
      marginTop: 6,
    },
    splashSubtitle: {
      color: '#ffffff',
      fontSize: 16,
      lineHeight: 24,
      textAlign: 'center',
      marginTop: 12,
    },
    homeIndicator: {
      position: 'absolute',
      bottom: 36,
      width: 70,
      height: 5,
      borderRadius: 5,
      backgroundColor: '#ffffff',
    },
    loginBody: {
      paddingHorizontal: 27,
      paddingTop: 66,
    },
    loginTitle: {
      fontSize: 23,
      fontWeight: '800',
      color: c.text,
      textAlign: 'center',
    },
    loginSubtitle: {
      color: c.textMuted,
      textAlign: 'center',
      fontSize: 14,
      marginTop: 8,
      marginBottom: 30,
    },
    fieldGroup: {
      marginBottom: 16,
    },
    fieldLabel: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 8,
    },
    inputWrap: {
      height: 52,
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
    },
    input: {
      flex: 1,
      fontSize: 15,
      color: c.text,
    },
    forgot: {
      alignSelf: 'flex-end',
      marginBottom: 24,
    },
    forgotText: {
      color: BLUE,
      fontSize: 12,
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    button: {
      height: 55,
      borderRadius: 7,
      backgroundColor: BLUE,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '800',
    },
    outlineButton: {
      backgroundColor: c.surface,
      borderWidth: 2,
      borderColor: BLUE,
    },
    outlineButtonText: {
      color: BLUE,
    },
    dangerButton: {
      borderColor: RED,
    },
    buttonDisabled: {
      opacity: 0.65,
    },
    dangerText: {
      color: RED,
    },
    errorText: {
      color: RED,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 14,
      textAlign: 'center',
    },
    orText: {
      textAlign: 'center',
      color: c.textMuted,
      fontSize: 12,
      marginVertical: 17,
    },
    header: {
      height: 56,
      paddingHorizontal: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerTitle: {
      color: c.text,
      fontSize: 18,
      fontWeight: '800',
    },
    iconSlot: {
      width: 42,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconButton: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeGrid: {
      paddingHorizontal: 24,
      paddingTop: 22,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 14,
    },
    menuCard: {
      width: (phoneWidth - 62) / 2,
      minHeight: 137,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#0c1a2e',
      shadowOpacity: 0.09,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    menuCardText: {
      color: c.text,
      fontSize: 13,
      fontWeight: '800',
      marginTop: 16,
    },
    bottomNav: {
      marginTop: 'auto',
      height: 72,
      borderTopWidth: 1,
      borderTopColor: c.line,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      backgroundColor: c.surface,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 92,
      gap: 5,
    },
    navLabel: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: '700',
    },
    navLabelActive: {
      color: BLUE,
    },
    content: {
      flex: 1,
      paddingHorizontal: 27,
      paddingTop: 18,
      paddingBottom: 28,
    },
    sectionIntro: {
      color: c.text,
      fontSize: 15,
      marginBottom: 18,
    },
    checkList: {
      gap: 22,
    },
    checkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    checkCircle: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 2,
      borderColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkCircleDisabled: {
      borderColor: RED,
    },
    checkLabel: {
      color: c.text,
      fontSize: 14,
      fontWeight: '800',
    },
    checkStatus: {
      color: c.textMuted,
      fontSize: 12,
      marginTop: 2,
    },
    checkStatusError: {
      color: RED,
      fontWeight: '700',
    },
    permissionHint: {
      color: RED,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 18,
      textAlign: 'center',
      marginBottom: 14,
    },
    flexSpacer: {
      flex: 1,
    },
    activeBody: {
      flex: 1,
      paddingHorizontal: 27,
      paddingTop: 10,
      paddingBottom: 28,
    },
    timerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginBottom: 18,
    },
    redDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      backgroundColor: RED,
    },
    timerText: {
      color: c.text,
      fontSize: 18,
      fontWeight: '700',
    },
    speedWrap: {
      height: 190,
      alignItems: 'center',
      justifyContent: 'center',
    },
    speedTextBlock: {
      position: 'absolute',
      top: 82,
      alignItems: 'center',
    },
    speedValue: {
      color: c.boldText,
      fontSize: 58,
      fontWeight: '900',
    },
    speedUnit: {
      color: c.boldText,
      fontSize: 18,
      fontWeight: '800',
      marginTop: 3,
    },
    metricGrid: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 13,
    },
    metricCard: {
      flex: 1,
      minHeight: 80,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.surface,
      shadowColor: '#0c1a2e',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    metricLabel: {
      color: c.text,
      fontSize: 11,
      fontWeight: '700',
      marginBottom: 8,
      textAlign: 'center',
    },
    metricValue: {
      color: c.text,
      fontSize: 18,
      fontWeight: '900',
      textAlign: 'center',
    },
    gpsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginTop: 34,
      marginBottom: 28,
    },
    greenDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: GREEN,
    },
    gpsText: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
    },
    centerBlock: {
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 22,
    },
    ringLabel: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringValue: {
      color: c.boldText,
      fontSize: 42,
      fontWeight: '900',
    },
    ringValueSmall: {
      fontSize: 18,
    },
    ringTotal: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
      marginTop: -3,
    },
    successText: {
      color: c.text,
      fontSize: 14,
      fontWeight: '800',
      marginTop: 18,
    },
    infoRows: {
      gap: 15,
      marginTop: 8,
      marginBottom: 16,
    },
    infoRowsCompact: {
      marginTop: 10,
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    infoLabel: {
      color: c.text,
      fontSize: 14,
      fontWeight: '700',
    },
    infoValue: {
      color: c.text,
      fontSize: 14,
      fontWeight: '900',
    },
    sectionTitle: {
      color: c.text,
      fontSize: 16,
      fontWeight: '900',
      marginTop: 8,
    },
    tabs: {
      height: 47,
      paddingHorizontal: 22,
      flexDirection: 'row',
      alignItems: 'flex-end',
      borderBottomWidth: 1,
      borderBottomColor: c.line,
    },
    tab: {
      flex: 1,
      height: 39,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    tabActive: {
      borderBottomColor: BLUE,
    },
    tabText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
    },
    tabTextActive: {
      color: BLUE,
    },
    historyList: {
      paddingHorizontal: 24,
      paddingBottom: 16,
    },
    emptyState: {
      textAlign: 'center',
      color: c.textMuted,
      fontSize: 14,
      fontWeight: '600',
      marginTop: 48,
    },
    historyItem: {
      minHeight: 86,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    historyDate: {
      color: c.text,
      fontSize: 14,
      fontWeight: '900',
    },
    historyMeta: {
      color: c.text,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 8,
    },
    resultsContent: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 24,
      gap: 14,
    },
    resultsHero: {
      minHeight: 146,
      borderRadius: 8,
      backgroundColor: c.sectionBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
    },
    resultsMonth: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    resultsScore: {
      color: c.boldText,
      fontSize: 52,
      fontWeight: '900',
      marginTop: 4,
    },
    resultsScoreLabel: {
      color: c.text,
      fontSize: 13,
      fontWeight: '800',
      marginTop: 2,
      textAlign: 'center',
    },
    resultStatsRow: {
      flexDirection: 'row',
      gap: 9,
    },
    resultStatTile: {
      flex: 1,
      minHeight: 72,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    resultStatValue: {
      color: c.text,
      fontSize: 18,
      fontWeight: '900',
    },
    resultStatLabel: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: '800',
      marginTop: 5,
      textTransform: 'uppercase',
    },
    resultChartCard: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.surface,
      paddingTop: 14,
      overflow: 'hidden',
    },
    resultChartHeader: {
      paddingHorizontal: 16,
      marginBottom: 3,
    },
    resultChartTitle: {
      color: c.text,
      fontSize: 15,
      fontWeight: '900',
    },
    resultChartSubtitle: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: '700',
      marginTop: 4,
    },
    detailsBody: {
      paddingHorizontal: 22,
      paddingBottom: 32,
    },
    detailsRatingCard: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.surface,
      paddingHorizontal: 14,
      paddingVertical: 14,
      marginTop: 10,
    },
    detailsStarRow: {
      flexDirection: 'row',
      gap: 6,
      marginBottom: 10,
    },
    detailsCommentText: {
      color: c.text,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 19,
    },
    dateCenter: {
      textAlign: 'center',
      color: c.text,
      fontSize: 12,
      fontWeight: '800',
      marginBottom: 16,
    },
    mapCard: {
      height: 170,
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: '#eff3ed',
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    ratingQuestion: {
      color: c.text,
      fontSize: 17,
      fontWeight: '900',
      marginTop: 20,
    },
    ratingAverageCard: {
      minHeight: 78,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.sectionBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      marginBottom: 22,
    },
    ratingAverageLabel: {
      color: c.text,
      fontSize: 13,
      fontWeight: '900',
    },
    ratingAverageMeta: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: '700',
      marginTop: 5,
    },
    ratingAverageValue: {
      color: c.boldText,
      fontSize: 25,
      fontWeight: '900',
    },
    ratingKeyboardAvoider: {
      flex: 1,
    },
    ratingContent: {
      flexGrow: 1,
      paddingHorizontal: 27,
      paddingTop: 18,
      paddingBottom: 28,
    },
    starRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 10,
      marginBottom: 28,
    },
    commentBox: {
      minHeight: 128,
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 8,
      padding: 15,
      color: c.text,
      textAlignVertical: 'top',
      fontSize: 15,
    },
    ratingReviewList: {
      gap: 11,
      paddingBottom: 10,
    },
    ratingReviewCard: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.surface,
      paddingHorizontal: 14,
      paddingVertical: 13,
    },
    ratingReviewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      marginBottom: 9,
    },
    ratingReviewDate: {
      flex: 1,
      color: c.text,
      fontSize: 12,
      fontWeight: '900',
    },
    ratingReviewStars: {
      flexDirection: 'row',
      gap: 2,
      flexShrink: 0,
    },
    ratingReviewComment: {
      color: c.text,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 19,
    },
    ratingReviewLink: {
      color: BLUE,
      fontSize: 12,
      fontWeight: '900',
      marginTop: 10,
    },
    challengeList: {
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 28,
      gap: 13,
    },
    challengeCard: {
      minHeight: 92,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.surface,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      gap: 12,
      shadowColor: '#0c1a2e',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    challengeIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    challengeText: {
      flex: 1,
    },
    challengeTitle: {
      color: c.text,
      fontSize: 14,
      fontWeight: '900',
    },
    challengeDescription: {
      color: c.text,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 3,
    },
    progressTrack: {
      height: 5,
      borderRadius: 4,
      backgroundColor: c.line,
      overflow: 'hidden',
      marginTop: 12,
    },
    progressFill: {
      height: '100%',
      borderRadius: 4,
    },
    progressText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '900',
      alignSelf: 'flex-end',
      marginBottom: 17,
    },
    profileBody: {
      flex: 1,
      alignItems: 'center',
      paddingTop: 34,
    },
    avatar: {
      width: 78,
      height: 78,
      borderRadius: 39,
      backgroundColor: '#7c858f',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: '#d3d8df',
    },
    avatarText: {
      color: '#ffffff',
      fontSize: 36,
      fontWeight: '800',
    },
    profileName: {
      color: c.text,
      fontSize: 24,
      fontWeight: '900',
    },
    profileNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 12,
    },
    profileEditButton: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileEditBlock: {
      width: '100%',
      alignItems: 'center',
      paddingHorizontal: 40,
      marginTop: 12,
    },
    profileNameInput: {
      width: '100%',
      height: 48,
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 7,
      paddingHorizontal: 14,
      color: c.text,
      fontSize: 18,
      fontWeight: '800',
      textAlign: 'center',
    },
    profileActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 10,
    },
    profileActionButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: c.line,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.surface,
    },
    profileError: {
      color: RED,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 8,
    },
    profileEmail: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 8,
    },
    profileSince: {
      color: c.textMuted,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 4,
    },
    profileStats: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: 34,
      paddingBottom: 26,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
    },
    stat: {
      alignItems: 'center',
      gap: 7,
    },
    statLabel: {
      color: c.text,
      fontSize: 10,
      fontWeight: '700',
    },
    statValue: {
      color: c.text,
      fontSize: 17,
      fontWeight: '900',
    },
    settingsList: {
      width: '100%',
      marginTop: 16,
    },
    settingsRow: {
      minHeight: 67,
      paddingHorizontal: 24,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    settingsRowText: {
      flex: 1,
      minWidth: 0,
    },
    settingsTrailing: {
      minWidth: 42,
      minHeight: 42,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    settingsTitle: {
      color: c.text,
      fontSize: 14,
      fontWeight: '900',
    },
    settingsSubtitle: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 8,
    },
    settingsSectionLabelWrap: {
      minHeight: 42,
      paddingHorizontal: 24,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: c.sectionBg,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
    },
    settingsSectionLabel: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    switchFrame: {
      width: 62,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    settingsSwitch: {
      transform: [{ scaleX: 0.86 }, { scaleY: 0.86 }],
    },
    segmentedControl: {
      width: 118,
      height: 36,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.inputBorder,
      flexDirection: 'row',
      overflow: 'hidden',
      backgroundColor: c.surface,
    },
    segmentOption: {
      flex: 1,
      minWidth: 58,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    segmentOptionActive: {
      backgroundColor: BLUE,
    },
    segmentText: {
      color: c.text,
      fontSize: 11,
      fontWeight: '800',
    },
    segmentTextActive: {
      color: '#ffffff',
    },
    // Threshold editor styles (SettingsScreen)
    thresholdSection: {
      paddingHorizontal: 24,
      paddingTop: 8,
      paddingBottom: 4,
      borderBottomWidth: 1,
      borderBottomColor: c.line,
    },
    thresholdRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
    },
    thresholdLabel: {
      flex: 1,
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
    },
    thresholdControls: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    thresholdStepBtn: {
      width: 30,
      height: 30,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.inputBorder,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    thresholdStepBtnText: {
      color: c.text,
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 22,
    },
    thresholdValueText: {
      width: 58,
      textAlign: 'center',
      color: c.text,
      fontSize: 13,
      fontWeight: '800',
    },
  });
}

const lightStyles = buildStyles(lightColors);
const darkStyles = buildStyles(darkColors);

export function useAppStyles() {
  const { isDark } = useTheme();
  return isDark ? darkStyles : lightStyles;
}
